name: UNTP Data models pre-release

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

    
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-1'
  # Setting an environment variable with the value of a configuration variable
  utility_jar: vocab-jsonld-utility-1.6.5.jar
  

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name}}
          path: spec-untp/

      - name: build data models matrix
        working-directory: spec-untp/data-models
        shell: bash
        id: data-models-matrix
        run: |
          find . -maxdepth 1 -type d -not -path . | sed 's/^.\///' | jq -R . | jq -s -c . > data-models.json
          cat data-models.json
          echo data-models=$(cat data-models.json) >> "$GITHUB_OUTPUT"


  publish-prerelease:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix:
        data-model: ${{ fromJSON(needs.define-matrix.outputs.data-models) }}

    steps: 
    - name: Update ${{ matrix.data-model }} 
      env:  
        data-model: ${{ matrix.data-model }}
      run: |
        echo "$data-model" 
      


