name: jargon_onRelease

on:
  workflow_call:
    
env:
  # Setting an environment variable with the value of a configuration variable
  domain_name: ${{ github.event.client_payload.domain.name }}
  prefix: ${{ github.event.client_payload.settings.jsonld.prefix }}
  version: ${{ github.event.client_payload.release.version }}

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          ref: data-models-staging
          token: ${{ steps.get_workflow_token.outputs.token }}
      
      - name: Check if release branch already exists
        id: checkout_release_branch
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          gh api repos/{owner}/{repo}/branches/feature/jargon-sync-${{ env.version }} >/dev/null 2>&1 && echo "release_branch=true" >> "$GITHUB_OUTPUT" || echo "Branch does not exist" 

      - uses: actions/checkout@v4
        if: steps.checkout_release_branch.outputs.release_branch
        with:
          ref: feature/jargon-sync-${{ env.version }}
          token: ${{ steps.get_workflow_token.outputs.token }}
      
      
      - run: 'echo "Domain name: ${{ env.domain_name }}"'
      - run: 'echo "client_payload: ${{ github.event.client_payload }}"'

      - name: Check if settings.jsonld.prefix is not blank
        run: '[ "${{ env.prefix }}" = "" ] && exit 1 || exit 0'
      
      - name: Check if ${{ env.prefix }} directory exists
        working-directory: "data-models/"
        run: '[ -d ${{ env.prefix }} ] || mkdir ${{ env.prefix }}'
      
      - name: Check if ${{ env.prefix }}/artefacts directory exists
        working-directory: "data-models/${{ env.prefix }}"
        run: '[ -d artefacts ] || mkdir artefacts'

      - shell: bash
        working-directory: "data-models/"
        env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}
        run: |
          printf '%s\n' "$CLIENT_PAYLOAD" > client_payload.json

      - name: Upload client payload
        uses: actions/upload-artifact@v4
        with:
          name: client-payload-${{ env.version }}
          path: data-models/client_payload.json
          
      - name: Cleanup client payload
        working-directory: "data-models/"
        run: |
          rm client_payload.json

      - name: Download files
        working-directory: "data-models/${{ env.prefix }}/"
        shell: bash
        run: |
          wget -O vocabulary.jsonld ${{ github.event.client_payload.artefacts.jsonldVocab.url }}
          wget -O artefacts/context.jsonld ${{ github.event.client_payload.artefacts.jsonldContext.url }}
          
          domain_schema=$(echo '${{ toJson(github.event.client_payload.artefacts.jsonSchemas) }}' | jq -r '.[0].url')
          domain_instance=$(echo '${{ toJson(github.event.client_payload.artefacts.jsonSchemas) }}' | jq -r '.[1].url')
          
          for schema_url in $(echo '${{ toJson(github.event.client_payload.artefacts.jsonSchemas) }}' | jq -r '.[].url'); do
            if [[ "$domain_schema" == "$schema_url" ]]; then
                filename="${{env.prefix }}-schema"
            elif [[ "$domain_instance" == "$schema_url" ]]; then
                filename="${{env.prefix }}-instance"
            else
              filename=${schema_url#*=}
              if [[ "$filename" =~ .*_instance$ ]]; then
                  filename=${filename//_/-}
              else
                  filename="$filename-schema"
              fi
            fi
            wget -O artefacts/${filename}.json $(echo "$schema_url" | sed 's/^"\|"$//g')
          done

      - name: Create/update pull request
        id: check
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

          git add .          
          git commit -m "feat: update ${{ github.event.client_payload.domain.name }} data model with Jargon release ${{ env.version }}" || echo -e "nothing to commit"
          
          git push origin feature/jargon-sync-${{ env.version }}
          prs=$(gh pr list \
              --head 'feature/jargon-sync-${{ env.version }}' \
              --base 'data-models-staging' \
              --json title,body)
          #TODO: add a check that there is a single match or none
          pr_title=$(echo $prs | jq -r '.[].title')
          if [[ "$pr_title" == "" ]]; then
            pr_title='feat: update data models with Jargon release ${{ env.version }}'
            gh pr create --title "$pr_title" --base data-models-staging --body "update ${{ github.event.client_payload.domain.name }} data model with Jargon release ${{ env.version }}"
          else
            gh pr edit --body "$(cat <<EOF
            echo $prs | jq -r '.[].body'
            update ${{ github.event.client_payload.domain.name }} data model with Jargon release ${{ env.version }}
            EOF
            )"
          fi
